apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: t3cyel4bc-python 
  janus-idp.io/tekton: t3cyel4bc-python
  backstage.io/kubernetes-id: t3cyel4bc-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: t3cyel4bc-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  